import { StyleSheet } from "react-native";

export const colors = {
  background: "#9fd3d1",
  ink: "#20312b",
  body: "#2f4a40",
  muted: "#536a5e",
  panel: "#fff7d0",
  paper: "#fbf6e8",
  border: "#486355",
  warning: "#9b4d42",
};

export const styles = StyleSheet.create({
  full: { flex: 1 },
  safeArea: { flex: 1, backgroundColor: colors.background },
  screen: { flexGrow: 1, gap: 14, padding: 18, backgroundColor: colors.background },
  title: { color: colors.ink, fontSize: 34, fontWeight: "900" },
  subtitle: { color: colors.body, fontSize: 16, lineHeight: 22 },
  input: {
    minHeight: 48,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    backgroundColor: colors.paper,
    color: colors.ink,
    fontSize: 16,
  },
  label: { color: colors.ink, fontSize: 13, fontWeight: "800", textTransform: "uppercase" },
  primaryButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    backgroundColor: colors.ink,
    paddingHorizontal: 14,
  },
  primaryButtonText: { color: colors.paper, fontSize: 16, fontWeight: "900" },
  secondaryButton: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: "#f7ead2",
    paddingHorizontal: 14,
  },
  secondaryButtonText: { color: colors.ink, fontSize: 15, fontWeight: "800" },
  disabledButton: { opacity: 0.42 },
  headerButton: {
    minHeight: 40,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: "#f7ead2",
    paddingHorizontal: 12,
  },
  listButton: {
    minHeight: 40,
    justifyContent: "center",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  listButtonText: { color: colors.ink, fontSize: 14, fontWeight: "700" },
  statusText: { color: colors.muted, fontSize: 14, fontWeight: "700" },
  warningText: { color: colors.warning, fontSize: 13, fontWeight: "800" },
  mutedText: { color: colors.muted, fontSize: 12, fontWeight: "700" },
  header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  metricsRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  metric: {
    minWidth: 82,
    borderWidth: 1,
    borderColor: "rgba(32,49,43,0.2)",
    borderRadius: 8,
    backgroundColor: "rgba(251,246,232,0.9)",
    padding: 9,
  },
  metricLabel: { color: colors.muted, fontSize: 11, fontWeight: "800" },
  metricValue: { color: colors.ink, fontSize: 15, fontWeight: "900", textTransform: "capitalize" },
  menuGrid: { gap: 10 },
  farmScreen: { flex: 1, backgroundColor: colors.background },
  scene: { flex: 1 },
  sceneOverlay: { position: "absolute", left: 0, right: 0, bottom: 0, paddingHorizontal: 12, paddingBottom: 8 },
  pickerRow: { gap: 8 },
  chip: {
    minHeight: 36,
    justifyContent: "center",
    borderRadius: 8,
    backgroundColor: "rgba(251,246,232,0.88)",
    paddingHorizontal: 10,
  },
  chipSelected: {
    minHeight: 36,
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.ink,
    borderRadius: 8,
    backgroundColor: colors.panel,
    paddingHorizontal: 10,
  },
  chipText: { color: colors.ink, fontSize: 12, fontWeight: "900" },
  topHud: { position: "absolute", top: 10, left: 10, right: 10, flexDirection: "row", flexWrap: "wrap", gap: 8 },
  bottomSheet: {
    maxHeight: "55%",
    gap: 10,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    backgroundColor: "rgba(251,246,232,0.96)",
    padding: 12,
  },
  sheetHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 },
  badge: {
    overflow: "hidden",
    borderRadius: 999,
    backgroundColor: colors.ink,
    color: colors.paper,
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "capitalize",
  },
  actionRow: { gap: 8 },
  inlineActions: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  actionButton: {
    minHeight: 40,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: colors.panel,
    paddingHorizontal: 12,
  },
  actionButtonText: { color: colors.ink, fontSize: 13, fontWeight: "900" },
  panel: {
    gap: 6,
    borderWidth: 1,
    borderColor: "rgba(32,49,43,0.18)",
    borderRadius: 8,
    backgroundColor: "rgba(255,247,208,0.55)",
    padding: 10,
  },
  subPanel: {
    gap: 3,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(32,49,43,0.18)",
    paddingTop: 6,
  },
  panelTitle: { color: colors.ink, fontSize: 15, fontWeight: "900" },
  bodyText: { color: colors.body, fontSize: 13, fontWeight: "700" },
  diagnostics: {
    gap: 5,
    borderWidth: 1,
    borderColor: "rgba(32,49,43,0.18)",
    borderRadius: 8,
    backgroundColor: "rgba(251,246,232,0.72)",
    padding: 10,
  },
  diagnosticsCompact: { gap: 3, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: "rgba(32,49,43,0.22)", paddingTop: 8 },
  progressTrack: { height: 8, borderRadius: 999, backgroundColor: "rgba(32,49,43,0.16)", overflow: "hidden" },
  progressFill: { height: 8, borderRadius: 999, backgroundColor: colors.ink },
  tileGrid: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  tileButton: {
    minWidth: 52,
    minHeight: 36,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: colors.paper,
    paddingHorizontal: 8,
  },
  splitRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  grow: { flexGrow: 1 },
});

