import { StyleSheet } from "react-native";

export const colors = {
  background: "#9fd3d1",
  ink: "#20312b",
  body: "#2f4a40",
  muted: "#536a5e",
  panel: "#fff7d0",
  paper: "#fbf6e8",
  border: "#486355",
  warning: "#9b4d42",
};

export const styles = StyleSheet.create({
  full: { flex: 1 },
  safeArea: { flex: 1, backgroundColor: colors.background },
  screen: { flexGrow: 1, gap: 10, padding: 12, backgroundColor: colors.background },
  title: { color: colors.ink, fontSize: 34, fontWeight: "900", lineHeight: 38 },
  subtitle: { color: colors.body, fontSize: 16, lineHeight: 22 },
  input: {
    minHeight: 48,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    backgroundColor: colors.paper,
    color: colors.ink,
    fontSize: 16,
  },
  label: { color: colors.ink, fontSize: 13, fontWeight: "800", textTransform: "uppercase" },
  primaryButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    backgroundColor: colors.ink,
    paddingHorizontal: 14,
  },
  primaryButtonText: { color: colors.paper, fontSize: 16, fontWeight: "900" },
  secondaryButton: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: "#f7ead2",
    paddingHorizontal: 14,
  },
  secondaryButtonText: { color: colors.ink, fontSize: 15, fontWeight: "800" },
  disabledButton: { opacity: 0.42 },
  headerButton: {
    minHeight: 40,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: "#f7ead2",
    paddingHorizontal: 12,
  },
  listButton: {
    minHeight: 40,
    justifyContent: "center",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  listButtonText: { color: colors.ink, fontSize: 14, fontWeight: "700" },
  statusText: { color: colors.muted, fontSize: 14, fontWeight: "700" },
  warningText: { color: colors.warning, fontSize: 13, fontWeight: "800" },
  mutedText: { color: colors.muted, fontSize: 12, fontWeight: "700" },
  header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12 },
  metricsRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  metric: {
    flexGrow: 1,
    minWidth: 0,
    borderWidth: 1,
    borderColor: "rgba(32,49,43,0.2)",
    borderRadius: 8,
    backgroundColor: "rgba(251,246,232,0.9)",
    padding: 9,
  },
  metricLabel: { color: colors.muted, fontSize: 11, fontWeight: "800" },
  metricValue: { color: colors.ink, fontSize: 15, fontWeight: "900", textTransform: "capitalize" },
  menuGrid: { gap: 8 },
  mainMenuScreen: {
    flex: 1,
    justifyContent: "center",
    padding: 12,
    backgroundColor: colors.background,
  },
  mainMenuPanel: {
    gap: 12,
    borderWidth: 1,
    borderColor: "rgba(32,49,43,0.28)",
    borderRadius: 8,
    backgroundColor: "rgba(251,246,232,0.97)",
    padding: 14,
  },
  mainMenuEyebrow: { color: colors.muted, fontSize: 13, fontWeight: "800" },
  mainMenuStats: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  mainMenuActions: { gap: 8 },
  mainMenuOptions: { gap: 8 },
  farmScreen: { flex: 1, backgroundColor: colors.background },
  scene: { flex: 1 },
  sceneOverlay: { position: "absolute", left: 0, right: 0, bottom: 0, paddingHorizontal: 12, paddingBottom: 8 },
  pickerRow: { gap: 8 },
  chip: {
    minHeight: 36,
    justifyContent: "center",
    borderRadius: 8,
    backgroundColor: "rgba(251,246,232,0.88)",
    paddingHorizontal: 10,
  },
  chipSelected: {
    minHeight: 36,
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.ink,
    borderRadius: 8,
    backgroundColor: colors.panel,
    paddingHorizontal: 10,
  },
  chipText: { color: colors.ink, fontSize: 12, fontWeight: "900" },
  topHud: { position: "absolute", top: 10, left: 10, right: 10, flexDirection: "row", flexWrap: "wrap", gap: 8 },
  bottomSheet: {
    maxHeight: "55%",
    gap: 10,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    backgroundColor: "rgba(251,246,232,0.96)",
    padding: 12,
  },
  sheetHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 },
  badge: {
    overflow: "hidden",
    borderRadius: 999,
    backgroundColor: colors.ink,
    color: colors.paper,
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 12,
    fontWeight: "900",
    textTransform: "capitalize",
  },
  actionRow: { gap: 8 },
  inlineActions: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  actionButton: {
    minHeight: 40,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: colors.panel,
    paddingHorizontal: 12,
  },
  actionButtonText: { color: colors.ink, fontSize: 13, fontWeight: "900" },
  panel: {
    gap: 6,
    borderWidth: 1,
    borderColor: "rgba(32,49,43,0.18)",
    borderRadius: 6,
    backgroundColor: "rgba(229,237,212,0.78)",
    padding: 10,
  },
  subPanel: {
    gap: 3,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(32,49,43,0.18)",
    paddingTop: 6,
  },
  panelTitle: { color: colors.ink, fontSize: 15, fontWeight: "900" },
  bodyText: { color: colors.body, fontSize: 13, fontWeight: "700" },
  diagnostics: {
    gap: 5,
    borderWidth: 1,
    borderColor: "rgba(32,49,43,0.18)",
    borderRadius: 8,
    backgroundColor: "rgba(251,246,232,0.72)",
    padding: 10,
  },
  diagnosticsCompact: { gap: 3, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: "rgba(32,49,43,0.22)", paddingTop: 8 },
  progressTrack: { height: 8, borderRadius: 999, backgroundColor: "rgba(32,49,43,0.16)", overflow: "hidden" },
  progressFill: { height: 8, borderRadius: 999, backgroundColor: colors.ink },
  tileGrid: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  tileButton: {
    minWidth: 52,
    minHeight: 36,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: colors.paper,
    paddingHorizontal: 8,
  },
  splitRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  grow: { flexGrow: 1 },
  mobileTopBar: {
    position: "absolute",
    top: 8,
    left: 8,
    right: 8,
    minHeight: 38,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    borderWidth: 1,
    borderColor: "rgba(32,49,43,0.25)",
    borderRadius: 8,
    backgroundColor: "rgba(247,239,221,0.94)",
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  levelProgressBadge: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 999,
    backgroundColor: colors.paper,
    borderWidth: 3,
    borderColor: "#6f9fd0",
  },
  levelProgressText: { color: colors.ink, fontSize: 13, fontWeight: "900" },
  hudChip: {
    minHeight: 30,
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderWidth: 1,
    borderColor: "rgba(32,49,43,0.18)",
    borderRadius: 999,
    backgroundColor: "rgba(255,253,245,0.8)",
    paddingHorizontal: 6,
  },
  hudChipCompact: {
    minHeight: 30,
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    borderWidth: 1,
    borderColor: "rgba(32,49,43,0.14)",
    borderRadius: 999,
    backgroundColor: "rgba(255,253,245,0.68)",
    paddingHorizontal: 5,
  },
  hudChipText: { color: colors.ink, fontSize: 11, fontWeight: "800" },
  storageSummaryChip: { flexDirection: "row", gap: 4 },
  mobileNotice: { flex: 1, minWidth: 0, color: colors.muted, fontSize: 11, fontWeight: "800" },
  mobileMenuButton: {
    minHeight: 32,
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: "#e5edd4",
    paddingHorizontal: 8,
  },
  mobileMenuButtonText: { color: colors.ink, fontSize: 12, fontWeight: "900" },
  mobileContextSheet: {
    position: "absolute",
    left: 8,
    right: 8,
    bottom: 132,
    maxHeight: 420,
    borderWidth: 1,
    borderColor: "rgba(32,49,43,0.24)",
    borderRadius: 10,
    backgroundColor: "rgba(251,246,232,0.97)",
    overflow: "hidden",
  },
  mobileContextPeek: {
    minHeight: 72,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 10,
  },
  mobileContextKicker: { color: colors.muted, fontSize: 12, fontWeight: "800" },
  mobileContextTitle: { color: colors.ink, fontSize: 18, fontWeight: "900", lineHeight: 20 },
  mobileContextDetail: { color: colors.muted, fontSize: 12, fontWeight: "800", lineHeight: 16 },
  mobileIconButton: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    backgroundColor: colors.panel,
  },
  mobileContextDetails: {
    maxHeight: 300,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(32,49,43,0.14)",
    padding: 10,
  },
  mobileActionStack: { gap: 8, paddingBottom: 10 },
  mobileResidentSwitcher: {
    position: "absolute",
    left: 8,
    right: 8,
    bottom: 132,
    maxHeight: 300,
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(32,49,43,0.24)",
    borderRadius: 10,
    backgroundColor: "rgba(251,246,232,0.97)",
    padding: 8,
  },
  mobileResidentRow: {
    gap: 3,
    borderWidth: 1,
    borderColor: "rgba(32,49,43,0.14)",
    borderRadius: 8,
    backgroundColor: colors.paper,
    padding: 9,
  },
  mobileToolPopover: {
    position: "absolute",
    left: 8,
    right: 8,
    bottom: 132,
    gap: 6,
    borderWidth: 1,
    borderColor: "rgba(32,49,43,0.24)",
    borderRadius: 10,
    backgroundColor: "rgba(251,246,232,0.97)",
    padding: 8,
  },
  mobileToolPopoverItem: {
    minHeight: 42,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(32,49,43,0.18)",
    borderRadius: 8,
    backgroundColor: colors.paper,
    paddingHorizontal: 9,
  },
  mobileToolPopoverItemActive: {
    borderColor: "#446d38",
    backgroundColor: colors.panel,
  },
  mobileToolPopoverText: { flex: 1, color: colors.ink, fontSize: 13, fontWeight: "900" },
  mobileToolPopoverCount: { color: colors.ink, fontSize: 13, fontWeight: "900" },
  mobileBuildDock: {
    position: "absolute",
    left: 8,
    right: 8,
    bottom: 84,
    gap: 6,
  },
  mobileBuildDetail: {
    minHeight: 54,
    gap: 2,
    borderWidth: 1,
    borderColor: "rgba(32,49,43,0.22)",
    borderRadius: 10,
    backgroundColor: "rgba(251,246,232,0.97)",
    padding: 9,
  },
  mobileBuildTray: {
    gap: 8,
    borderWidth: 1,
    borderColor: "rgba(32,49,43,0.22)",
    borderRadius: 10,
    backgroundColor: "rgba(247,239,221,0.97)",
    padding: 8,
  },
  mobileBuildCard: {
    width: 144,
    minHeight: 82,
    gap: 3,
    borderWidth: 1,
    borderColor: "rgba(32,49,43,0.18)",
    borderRadius: 8,
    backgroundColor: colors.paper,
    padding: 8,
  },
  mobileBuildCardActive: { borderColor: "#446d38", backgroundColor: colors.panel },
  mobileBuildIcon: { color: colors.ink, fontSize: 18, fontWeight: "900" },
  mobileBuildTitle: { color: colors.ink, fontSize: 13, fontWeight: "900" },
  mobileBuildMeta: { color: colors.muted, fontSize: 11, fontWeight: "800" },
  mobileResidentChip: {
    position: "absolute",
    left: 8,
    bottom: 86,
    maxWidth: 180,
    minHeight: 38,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    borderWidth: 1,
    borderColor: "rgba(32,49,43,0.22)",
    borderRadius: 8,
    backgroundColor: "rgba(251,246,232,0.97)",
    paddingHorizontal: 9,
  },
  mobileResidentChipText: { flexShrink: 1, color: colors.ink, fontSize: 13, fontWeight: "900" },
  mobileResidentQueue: {
    minWidth: 22,
    overflow: "hidden",
    borderRadius: 999,
    backgroundColor: "rgba(68,109,56,0.16)",
    color: colors.ink,
    paddingHorizontal: 6,
    textAlign: "center",
    fontSize: 12,
    fontWeight: "900",
  },
  mobileToolStatus: {
    position: "absolute",
    right: 8,
    bottom: 88,
    maxWidth: 176,
    borderWidth: 1,
    borderColor: "rgba(32,49,43,0.16)",
    borderRadius: 8,
    backgroundColor: "rgba(251,246,232,0.97)",
    paddingHorizontal: 9,
    paddingVertical: 7,
  },
  mobileToolStatusText: { color: colors.muted, fontSize: 12, fontWeight: "800" },
  mobileActionBar: {
    position: "absolute",
    left: 8,
    right: 8,
    bottom: 8,
    flexDirection: "row",
    gap: 6,
    borderWidth: 1,
    borderColor: "rgba(32,49,43,0.24)",
    borderRadius: 12,
    backgroundColor: "rgba(247,239,221,0.97)",
    padding: 7,
  },
  mobileActionButton: {
    flex: 1,
    minWidth: 58,
    minHeight: 58,
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
    borderWidth: 1,
    borderColor: "rgba(32,49,43,0.18)",
    borderRadius: 8,
    backgroundColor: colors.paper,
    paddingHorizontal: 4,
  },
  mobileActionButtonActive: {
    borderColor: "#446d38",
    backgroundColor: colors.panel,
  },
  mobileActionButtonText: { color: colors.ink, fontSize: 11, fontWeight: "900" },
});
